<div style="display:fill;
           border-radius:5px;
           background-color:#FFFCFF;
           font-family:Harlow Solid;
           letter-spacing:0.1px;
           text-align: center;
           margin: auto;">
<u><h1 style ="font-size:55px; color:#546A76; text-shadow: 2px 2px #DBE2E6;">Data Quality</h1></u>
<h3 style = "font-size:15px; font-family:Gotham Heavy; color:#546A76;letter-spacing:0.1px;">DS411 - Predictive Analytics</h3>
</h1>
</div>

## What is Data Quality?

`Data quality` measures how well a dataset meets criteria for accuracy, completeness, validity, consistency, uniqueness, timeliness and fitness for purpose, and it is critical to all data governance initiatives within an organization. It is very important that data have good quality to make decisions on trustworthy data and to lead correct and reliable analysis.

## Why Is Data Quality Important?

Data quality is crucial as it affects the precision and trustworthiness of information used in decision-making. Accurate and reliable data is essential for making well-informed choices. Although all data has some level of "quality," various factors and characteristics determine whether the data is of high or low quality.

## Dimensions of Data Quality

According to [IBM](https://www.ibm.com/topics/data-quality#:~:text=Data%20quality%20measures%20how%20well,governance%20initiatives%20within%20an%20organization), Data quality is evaluated based on a number of dimensions, which can differ based on the source of information. These dimensions are used to categorize data quality metrics:

1. **Completeness**
   - This refers to the amount of data that is useable or complete. A large percentage of missing values may result in a skewed or misleading analysis if the data is not representative of a normal data sample. Incomplete data is not the same as inaccurate data, as you can have a complete data set and the information still be incorrect. Data completeness should get measured across entire records, and not just at the item level.
2. **Timeliness**
   - Timeliness assesses how current or outdated the data is at any particular time. For example, if you have client information from 2008 and it is now 2021, there will be a problem with the data's timeliness and completeness. When evaluating data quality, timeliness can greatly influence its overall accuracy, relevance, and reliability, either positively or negatively.
4. **Validity**
   - This dimension assesses how much data adheres to the acceptable format for any business rules. Formatting typically comprises metadata such as appropriate data types, ranges, patterns, and so on. Ensuring data validity involves setting specific criteria that the data must satisfy within an organization. This allows the data to be integrated with other sources and helps improve the efficiency of automated data processes.
6. **Integrity**
   - Data integrity refers to how reliable and trustworthy the information is. It involves ensuring that the data is accurate and factual. For instance, if a customer’s email address in your database is outdated because the customer deleted the account years ago, this would highlight a problem with both data integrity and timeliness.
8. **Uniqueness**
   - As the name implies, this dimension measures the redundancy of the same record in a dataset. A high-quality dataset, in terms of uniqueness, should be de-duplicated.
10. **Consistency**
    - Consistent data occurs when all records are uniform across various datasets. It is crucial because it enhances the ability to integrate data from different sources, improving overall usability. Inconsistent data often arises from duplicate records or the absence of standardized data entry processes. For example, a customer’s details might include both an old and a new phone number, leading to unreliable data. Similarly, failing to standardize date formats, such as using mm/dd/yyyy, can result in conflicting data for important fields like birth dates or contract end dates.

# Natural Language Toolkit

`NLTK` is an <u>open-source library</u> that simplifies the complexities of natural language processing (NLP). It offers functionalities for tasks like tokenization, stemming, tagging, parsing, and more. NLTK is widely used in academia and industry for building applications involving text analysis, sentiment analysis, language understanding, and machine learning.

## What is Text Processing?

`Text processing` is the technique of transforming and analyzing textual data to make it easier to work with, especially for tasks like text mining, natural language processing (NLP), and machine learning. It involves cleaning, structuring, and preparing text so that it can be analyzed more effectively.

## Key steps in Text Processing

- **Tokenization**
    - The breaking down of text into smaller units is called tokens. tokens are a small part of that text. If we have a sentence, the idea is to separate each word and build a vocabulary such that we can represent all words uniquely in a list. Numbers, words, etc.. all fall under tokens.
      - ***Word Tokenization*** - is the process of splitting a sentence or text into individual words or tokens.
      - ***Sentence Tokenization*** - (or segmentation) is the process of splitting text into individual sentences.
    > Note: Basically its like using .split() function to split your text into a list.
- **Word Casing**
  - In text processing, while `lowercasing` is commonly used for standardizing text, there are situations where `uppercasing` or `title casing` (capitalizing the first letter of each word) might be required.
- **Stop words**
  - When presented features from a text to model, we might encounter a lot of noise. Removing common words like "the," "is," or "and" that do not contribute significant meaning to the analysis. With NLTK we can see all the stop words available in the English language.
- **Contractions**
  - Contractions are often expanded into their full forms to maintain uniformity and accuracy in text analysis. This step is critical since contractions like "can't" or "won't" are abbreviated forms of "cannot" and "will not," and failing to expand them may result in errors in text processing.
- **Stemming**
  - Stemming is the process of reducing a word to its root or stem by chopping off its suffixes or prefixes. The result may not always be a valid word, but it serves as a rough approximation to group similar words together. How it works is that it uses simple heuristic rules to remove common word endings, such as "-ing", "-ed", "-ly", "-s", etc.
  - uses simple heuristic rules to remove common word endings, such as "-ing", "-ed", "-ly", "-s", etc. It doesn’t take into account the meaning of the word or context, leading to quick and computationally efficient results.
    * Types of Stemming:
        - Porter Stemmer: One of the most commonly used stemming algorithms. It follows a set of rules to iteratively trim words down to their base form.
        - Lancaster Stemmer: A more aggressive stemming algorithm that removes larger chunks from words but may lead to over-stemming (too much truncation).
        - Snowball Stemmer: An improvement over Porter stemming, it’s also known as the English Stemmer and is more flexible in handling word forms.
| Word | Porter | Lancaster |
| ---- | ------ | ----------|
|"running"|	"run"|	"run"|
|"runner"|	"run"|	"run"|
|"happily"|	"happili"|	"happy"|
|"studies"|	"studi"|	"study"|
|"studying"|	"studi"|	"study"|


- **Lemmatization**
  -  is the process of reducing a word to its lemma, or dictionary form, after evaluating its meaning and part of speech. Unlike stemming, lemmatization generates an appropriate word in the language. It uses more complex process, often relying on a vocabulary or lexical database (like WordNet) to look up words and return their canonical form based on their context, such as whether they are nouns, verbs, or adjectives.
    * Types of Lemmatization:
      - Rule-based Lemmatization: Relies on a set of rules to transform inflected words into their root form based on their part of speech.
      - Dictionary-based Lemmatization: Uses a lookup table (like WordNet) to find the base form of words.
|   Word	|  Lemmatization (Verb)  |	Lemmatization (Noun)  |
|-----------|------------------------|------------------------|
|"running"  |	"run"                |            "run"       |
|"better"   |	"good"               |         "better"       |
|"geese"    |	"goose"              |          "goose"       |
|"studies"  |	"study"              |          "study"       |
|"studying" |	"study"              |          "study"       |
> Note: Lemmatization accurately returns meaningful words by considering context. For example, "better" as an adjective returns "good," while as a verb it remains "better."<br>

### Addt'l Info: 
#### ***Regex*** or Regular Expression

***Regular expressions*** (regex or regexp) are extremely useful in extracting information from any text by searching for one or more matches of a specific search pattern (i.e. a specific sequence of ASCII or unicode characters).

***[Here is an in-depth understanding on RegEx](https://medium.com/@victoriousjvictor/understanding-regular-expressions-regex-e1c048f5aa6c)*** <br>
***[Additional Information, ](https://archive.is/63sjK#selection-613.0-617.125)*** this is to go through some patterns and additional examples.

### Import necessary Packages

In [1]:
import nltk 
import re # for Regex
import string

In [2]:
# nltk.download('punkt_tab')
# nltk.download('wordnet')
# nltk.download('stopwords')

In [3]:
myCorpus = [" The quick brown fox wasn't that quick and he couldn't win the race",
         "Hey! That's a grete deal! I just bought a \phone at $144 ",
         "@@You'll (learn) a **lot** in the book. Python fox is an amaewzing langage !@@"]

In [4]:
len(myCorpus)

3

### Remove Punctuation

In [5]:
def rem_punct(my_str):
    
    if my_str is None:
        return None
    
    punctuations = '''!¡()-[]{};:'.'"“”`\,.<>/|?@#$%^—-=&_+0123456789•~*…''' 

    no_punct = ""
    for char in my_str:
        if char not in punctuations:
            no_punct += char
    return no_punct

In [6]:
for y in myCorpus:
    rempunct = rem_punct(y)
    print(rempunct)

 The quick brown fox wasnt that quick and he couldnt win the race
Hey Thats a grete deal I just bought a phone at
Youll learn a lot in the book Python fox is an amaewzing langage

### Tokenization

In [7]:
def sent_tokenize(text):
    word_tokens = nltk.sent_tokenize(text)
    return word_tokens

def word_tokenize(text):
    word_tokens = nltk.word_tokenize(text)
    return word_tokens

In [8]:
new_list = [rem_punct(sentence) for sentence in myCorpus]
for word in new_list:
    token = word_tokenize(word)
    print(token)

['The', 'quick', 'brown', 'fox', 'wasnt', 'that', 'quick', 'and', 'he', 'couldnt', 'win', 'the', 'race']
['Hey', 'Thats', 'a', 'grete', 'deal', 'I', 'just', 'bought', 'a', 'phone', 'at']
['Youll', 'learn', 'a', 'lot', 'in', 'the', 'book', 'Python', 'fox', 'is', 'an', 'amaewzing', 'langage']

In [9]:
sentence_corpus = 'Hello World! I found a new hobby to do. How is life?'

token_sent = sent_tokenize(sentence_corpus)
for sentence in token_sent:
    print(sentence)

Hello World!
I found a new hobby to do.
How is life?

### Removing Repeating Letters

In [10]:
from nltk.corpus import wordnet

def removeRepeatedCharacters(tokens):
    repeatPattern = re.compile(r'(\w*)(\w)\2(\w*)')
    
    def replace(word):
        while not wordnet.synsets(word):
            newWord = repeatPattern.sub(r'\1\2\3', word)
            if newWord == word:
                break
            word = newWord
        return word

    return [replace(word) for word in tokens]

> ***Wild Regex pattern appeared!*** <br>
> r'(\w*)(\w)\2(\w*)' This pattern looks for repeated characters. The \2 refers to the second group, meaning it captures any character repeated consecutively.

>r'\1\2\3': This pattern replaces the repeated characters with a single occurrence.

In [11]:
sentence = ' My Schoooooool is reeeeeeaaaallllllllly amaaaaaazingggg!'

sampleSentence = word_tokenize(sentence)
print("Original Sentence ", sampleSentence)
print("Corrected Sentence ", removeRepeatedCharacters(sampleSentence))

Original Sentence  ['My', 'Schoooooool', 'is', 'reeeeeeaaaallllllllly', 'amaaaaaazingggg', '!']
Corrected Sentence  ['My', 'School', 'is', 'realy', 'amazing', '!']

### Word Contraction

In [12]:
import contractions

for word in new_list:
    contra = contractions.fix(word)
    token = word_tokenize(contra)
    print(token)

['The', 'quick', 'brown', 'fox', 'was', 'not', 'that', 'quick', 'and', 'he', 'could', 'not', 'win', 'the', 'race']
['Hey', 'That', 'Is', 'a', 'grete', 'deal', 'I', 'just', 'bought', 'a', 'phone', 'at']
['You', 'Will', 'learn', 'a', 'lot', 'in', 'the', 'book', 'Python', 'fox', 'is', 'an', 'amaewzing', 'langage']

### Remove Stop words

In [13]:
from nltk.corpus import stopwords

def remove_stopwords_orig(text):
    global filtered_words
    stopWords = set(stopwords.words('english'))
    
    filtered_words = []
    for w in text:
        if w not in stopWords:
            filtered_words.append(w)
            filtered_words.append(' ')
           
    return "".join(filtered_words)

In [14]:
for word in new_list:
    word = word.lower()
    contra = contractions.fix(word)
    token = word_tokenize(contra)
    no_stopwords = remove_stopwords_orig(token)
    print(no_stopwords)

quick brown fox quick could win race
hey grete deal bought phone
learn lot book python fox amaewzing langage

> *Note*: <br>The stopwords list provided by nltk (or similar libraries) contains only lowercase versions of words. This is typical because stopwords are usually considered case-insensitive. If your input text has capitalized words (like "Is" or "I"), they will not match with the lowercase stopwords unless you normalize the case by converting all words to lowercase.

### Spelling

In [15]:
from autocorrect import Speller

def check_spelling(text):
    spellcheck = Speller(lang='en')
    return spellcheck(text)

In [16]:
for word in new_list:
    word = word.lower()
    contra = contractions.fix(word)
    token = word_tokenize(contra)
    no_stopwords = remove_stopwords_orig(token)
    corr_spell = check_spelling(no_stopwords)
    print(corr_spell)

quick brown fox quick could win race
hey greet deal bought phone
learn lot book python fox amazing language

### Stemming

In [17]:
from nltk.stem import PorterStemmer
from nltk.stem import LancasterStemmer
from nltk.stem.snowball import SnowballStemmer

port_stem = PorterStemmer()
lancas_stem = LancasterStemmer()
snowb_stem = SnowballStemmer(language='english')

In [18]:
display(port_stem.stem('studying'),
       lancas_stem.stem('studying'),
       snowb_stem.stem('studying'))
print('----'*20)
display(port_stem.stem('running'),
       lancas_stem.stem('running'),
       snowb_stem.stem('running'))
print('----'*20)
display(port_stem.stem('costly'),
       lancas_stem.stem('costly'),
       snowb_stem.stem('costly'))

'studi'

'study'

'studi'

--------------------------------------------------------------------------------

'run'

'run'

'run'

--------------------------------------------------------------------------------

'costli'

'cost'

'cost'

### Lemmatization

In [19]:
from nltk.stem import WordNetLemmatizer

wlm = WordNetLemmatizer()

In [20]:
display(wlm.lemmatize('understanding', 'v'),
        wlm.lemmatize('running', 'v'),
        wlm.lemmatize('happiest', 'a'),
        wlm.lemmatize('children', 'n'))

'understand'

'run'

'happy'

'child'

---

In [21]:
corr_list = []
for word in new_list:
    word = word.lower()
    contra = contractions.fix(word)
    token = word_tokenize(contra)
    no_stopwords = remove_stopwords_orig(token)
    corr_spell = check_spelling(no_stopwords)
    corr_list.append(corr_spell)
    
for sentence in corr_list:
    token = word_tokenize(sentence)
    for word in token:
        word = wlm.lemmatize(word, 'v')
        print(word)

quick
brown
fox
quick
could
win
race
hey
greet
deal
buy
phone
learn
lot
book
python
fox
amaze
language

As you can see, removing punctuations, expanding contractions, and spell checking are included here without the need for the NLTK Python package. These tasks help de-clutter our textual data, making it cleaner for more accurate analysis. These functions are part of what we call ***Data Cleaning***!

# Data Cleaning

## Data Preprocessing and Data Normalization in Text Data

<font size=4px><b><i>Data Preprocessing</i></b></font>
- for text involves a series of steps to clean, format, and transform raw text into a structured and analyzable form. It is the first stage before applying any machine learning or natural language processing (NLP) models.
> <b>Goal</b>: To reduce noise and prepare the text for further analysis by ensuring it's structured, clean, and ready for modeling.



<font size=4px><b><i>Data Normalization</i></b></font>
- refers to techniques used to standardize and format the text consistently. This ensures that variations in word forms, cases, and other features don't confuse text analysis models.
> <b>Goal</b>: To standardize and simplify the text by reducing variations and inconsistencies so that machine learning models can interpret it effectively.

In the context of Text Data, `Data Preprocessing` and `Data Normalization` are not *separate* stages, but rather integrated components of the same workflow that help us prepare unstructured text for deeper analysis.

Consider Data Preprocessing to be a comprehensive procedure that includes tasks such as cleaning, organizing, and altering raw text. Tokenization, stopword removal, and dealing with noisy data like punctuation and special characters are all difficulties that must be addressed during preprocessing. These are the core tasks that will ensure that our material is manageable for analysis.

Within this larger process, Data Normalization serves as a more targeted stage. Normalization ensures text consistency by standardizing diverse representations of the same information. 

Normalization, whether by converting everything to lowercase, extending contractions, or consistently formatting numbers and dates, helps us reduce variability and ensure that our research is not thrown off by little, inconsequential variances in the data.

For example, in a preprocessing work, we might have tokenized a sentence and deleted stopwords. Then, normalization assures that changes in word forms (for example, 'USA' vs. 'usa') do not result in inaccurate textual insights.

Thus, Data Normalization is an important subset of Data Preprocessing, especially when dealing with textual data, and they work together to lay the groundwork for any text-based data science tasks. Without proper preprocessing and normalization, our models may struggle to derive useful insights from the data.

---

### Import Packages

In [22]:
import pandas as pd
import nltk

from sqlalchemy import create_engine
import json
import pdfplumber
import requests
from bs4 import BeautifulSoup
import unicodedata

import os
from tqdm.notebook import tqdm
import warnings
warnings.filterwarnings('ignore')

### Json Movie Dataset

In [23]:
path = './Datasets/movies/'
movies = os.listdir(path)
movie_list = list()

for years in tqdm(movies):
    for movie in os.listdir(os.path.join(f'{path}', f'{years}')):
        with open(os.path.join(f'{path}', f'{years}', f'{movie}'), encoding="ISO-8859-1") as movie_jsn:
            movie_list.append(json.load(movie_jsn))

  0%|          | 0/67 [00:00<?, ?it/s]

In [24]:
movie_df = pd.DataFrame(movie_list)
movie_df = movie_df.applymap(lambda x: None if isinstance(x, str) and x.strip() == '' else x)
# movie_df

## Data Normalization (Sample For DataFrames)

### Data Types

In [25]:
movie_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 472 entries, 0 to 471
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          472 non-null    object
 1   year          472 non-null    int64
 2   runtime       471 non-null    object
 3   categories    470 non-null    object
 4   release-date  470 non-null    object
 5   director      471 non-null    object
 6   writer        472 non-null    object
 7   actors        472 non-null    object
 8   storyline     419 non-null    object
 9   description   26 non-null     object
 10  future        11 non-null     object
 11  plot          6 non-null      object
 12  released      2 non-null      object
 13  genre         1 non-null      object
 14  category      1 non-null      object
 15  directors     1 non-null      object
dtypes: int64(1), object(15)
memory usage: 59.1+ KB

In [26]:
# ----- for integers and float ----- #
for cols in ['year', 'runtime']:
    movie_df[cols] = pd.to_numeric(movie_df[cols], errors='coerce')
# or you can use df[column].astype('int64') or df[column].astype('float64')

# ----- for strings ----- #
movie_df[['name','categories', 'director', 
          'writer', 'actors', 'storyline']] = movie_df[['name','categories', 'director', 
                                                        'writer', 'actors', 'storyline']].astype(str)

### Word Casing

In [27]:
movie_df['name'] = movie_df['name'].str.upper()
movie_df
# or you can do: movie_df['name'] = movie_df['name'].str.lower()
# or: movie_df['name'] = movie_df['name'].str.title()

,name,year,runtime,categories,release-date,director,writer,actors,storyline,description,future,plot,released,genre,category,directors
0,THE WIZARD OF OZ,1925,81.0,"['comedy', 'family', 'fantasy']",1925-01-27,Larry Semon,"['L. Frank Baum', 'Frank Joslyn Baum', 'Edgar ...","['Dorothy Dwan', 'Mary Carr', 'Virginia Pearso...","Dorothy, heir to the Oz throne, must take it b...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,FRANKENSTEIN,1931,70.0,"['drama', 'horror', 'sci-fi']",1931-09-21,James Whale,"['John L. Balderston', 'Mary Shelley']","['Colin Clive', 'Mae Clarke', 'John Boles', 'B...",Henry Frankenstein is a doctor who is trying t...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,KING KONG,1933,100.0,"['adventure', 'horror', 'sci-fi']",1933-04-07,"['Merian C. Cooper', 'Ernest B. Schoedsack']","['James Ashmore Creelman', 'Ruth Rose', 'Meria...","['Fay Wray', 'Robert Armstrong', 'Bruce Cabot'...",A film crew goes to a tropical island for an e...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,THE INVISIBLE MAN,1933,71.0,"['horror', 'sci-fi']",1933-11-03,James Whale,"['H.G. Wells', 'R.C. Sherriff']","['Claude Rains', 'William Harrigan', 'Gloria S...","A stranger, his face covered in bandages takes...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,THE ADVENTURES OF ROBIN HOOD,1938,102.0,"['action', 'adventure', 'romance']",1938-05-14,"['Michael Curtiz', 'William Keighley']","['Norman Reilly Raine', 'Seton I. Miller']","['Errol Flynn', 'Olivia de Havilland', 'Basil ...",When Prince John and the Norman Lords begin op...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
467,THE INVISIBLE MAN,2020,124.0,"['horror', 'thriller', 'sci-fi']",2020-02-28,Leigh Whannell,['Leigh Whannell'],"['Elisabeth Moss', 'Aldis Hodge', 'Storm Reid'...",It follows a woman who believes she is being s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
468,BLACK WIDOW,2021,134.0,"['sci-fi', 'action', 'adventure']",2021-07-09,['Cate Shortland'],['Eric Pearson'],"['Scarlett Johansson', 'Florence Pugh', 'Rache...","Natasha Romanoff, aka Black Widow, confronts t...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
469,CRUELLA,2021,134.0,"['adventure', 'comedie', 'crime']",2021-05-18,['Craig Gillespie'],"['Dana Fox', 'Tony McNamara']","['Emma Stone', 'Emma Thompson', 'Joel Fry', 'P...",Estella is a young and clever grifter who's de...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
470,ETERNALS,2021,157.0,"['drama', 'adventure', 'action']",2021-10-18,Chloe Zhao,"['Chloe Zhao', 'Patrick Burleigh', 'Ryan Firpo...","['Gemma Chan', 'Richard Madden', 'ThÃ©odore Pe...","The saga of the Eternals, a race of immortal b...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
471,RAYA AND THE LAST DRAGON,2021,124.0,"['animation', 'action', 'adventure']",2021-03-04,"['Don Hall', 'Carlos LÃ³pez Estrada']","['Qui Nguyen', 'Adele Lim']","['Kelly Marie Tran', 'Awkwafina', 'Izaac Wang'...","Long ago, in the fantasy world of Kumandra, hu...",NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Date Formats

In [28]:
# -------- Nomralize the data's date to YYYY-MM-DD -------- #
movie_df['release-date'] = pd.to_datetime(movie_df['release-date'], format='%Y-%m-%d', errors='coerce')
display(movie_df, movie_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 472 entries, 0 to 471
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          472 non-null    object
 1   year          472 non-null    int64
 2   runtime       471 non-null    float64
 3   categories    472 non-null    object
 4   release-date  464 non-null    datetime64[ns]
 5   director      472 non-null    object
 6   writer        472 non-null    object
 7   actors        472 non-null    object
 8   storyline     472 non-null    object
 9   description   26 non-null     object
 10  future        11 non-null     object
 11  plot          6 non-null      object
 12  released      2 non-null      object
 13  genre         1 non-null      object
 14  category      1 non-null      object
 15  directors     1 non-null      object
dtypes: datetime64[ns](1), float64(1), int64(1), object(13)
memory usage: 59.1+ KB

,name,year,runtime,categories,release-date,director,writer,actors,storyline,description,future,plot,released,genre,category,directors
0,THE WIZARD OF OZ,1925,81.0,"['comedy', 'family', 'fantasy']",1925-01-27,Larry Semon,"['L. Frank Baum', 'Frank Joslyn Baum', 'Edgar ...","['Dorothy Dwan', 'Mary Carr', 'Virginia Pearso...","Dorothy, heir to the Oz throne, must take it b...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,FRANKENSTEIN,1931,70.0,"['drama', 'horror', 'sci-fi']",1931-09-21,James Whale,"['John L. Balderston', 'Mary Shelley']","['Colin Clive', 'Mae Clarke', 'John Boles', 'B...",Henry Frankenstein is a doctor who is trying t...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,KING KONG,1933,100.0,"['adventure', 'horror', 'sci-fi']",1933-04-07,"['Merian C. Cooper', 'Ernest B. Schoedsack']","['James Ashmore Creelman', 'Ruth Rose', 'Meria...","['Fay Wray', 'Robert Armstrong', 'Bruce Cabot'...",A film crew goes to a tropical island for an e...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,THE INVISIBLE MAN,1933,71.0,"['horror', 'sci-fi']",1933-11-03,James Whale,"['H.G. Wells', 'R.C. Sherriff']","['Claude Rains', 'William Harrigan', 'Gloria S...","A stranger, his face covered in bandages takes...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,THE ADVENTURES OF ROBIN HOOD,1938,102.0,"['action', 'adventure', 'romance']",1938-05-14,"['Michael Curtiz', 'William Keighley']","['Norman Reilly Raine', 'Seton I. Miller']","['Errol Flynn', 'Olivia de Havilland', 'Basil ...",When Prince John and the Norman Lords begin op...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
467,THE INVISIBLE MAN,2020,124.0,"['horror', 'thriller', 'sci-fi']",2020-02-28,Leigh Whannell,['Leigh Whannell'],"['Elisabeth Moss', 'Aldis Hodge', 'Storm Reid'...",It follows a woman who believes she is being s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
468,BLACK WIDOW,2021,134.0,"['sci-fi', 'action', 'adventure']",2021-07-09,['Cate Shortland'],['Eric Pearson'],"['Scarlett Johansson', 'Florence Pugh', 'Rache...","Natasha Romanoff, aka Black Widow, confronts t...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
469,CRUELLA,2021,134.0,"['adventure', 'comedie', 'crime']",2021-05-18,['Craig Gillespie'],"['Dana Fox', 'Tony McNamara']","['Emma Stone', 'Emma Thompson', 'Joel Fry', 'P...",Estella is a young and clever grifter who's de...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
470,ETERNALS,2021,157.0,"['drama', 'adventure', 'action']",2021-10-18,Chloe Zhao,"['Chloe Zhao', 'Patrick Burleigh', 'Ryan Firpo...","['Gemma Chan', 'Richard Madden', 'ThÃ©odore Pe...","The saga of the Eternals, a race of immortal b...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
471,RAYA AND THE LAST DRAGON,2021,124.0,"['animation', 'action', 'adventure']",2021-03-04,"['Don Hall', 'Carlos LÃ³pez Estrada']","['Qui Nguyen', 'Adele Lim']","['Kelly Marie Tran', 'Awkwafina', 'Izaac Wang'...","Long ago, in the fantasy world of Kumandra, hu...",NaN,NaN,NaN,NaN,NaN,NaN,NaN

None

## Data Preprocessing (Sample For DataFrames)

### Finding Null Values
<font size='2px'>At this point, we are only focusing on the <u>name</u> column up to the <u>storyline</u> column</font>

In [29]:
movie_df.isnull().sum()

name              0
year              0
runtime           1
categories        0
release-date      8
director          0
writer            0
actors            0
storyline         0
description     446
future          461
plot            466
released        470
genre           471
category        471
directors       471
dtype: int64

In [30]:
movie_df[movie_df['runtime'].isna()]

,name,year,runtime,categories,release-date,director,writer,actors,storyline,description,future,plot,released,genre,category,directors
400,OVERLORD,2018,NaN,"['Action', 'Horror', 'Mystery']",2018-10-26,Julius Avery,"['Billy Ray', 'Billy Ray']","['Wyatt Russell', 'Pilou AsbÃ¦k', 'Bokeem Wood...",nan,NaN,True,"On the eve of D-Day, American paratroopers are...",NaN,NaN,NaN,NaN

In [31]:
movie_df[movie_df['release-date'].isna()]

,name,year,runtime,categories,release-date,director,writer,actors,storyline,description,future,plot,released,genre,category,directors
27,LA PATAGONIA REBELDE,1974,103.0,"['historical', 'drama', 'action']",NaT,Hector Olivera,"['Fernando Ayala', 'Hector Olivera', 'Osvaldo ...","['Hector Alterio', 'Luis Brandoni', 'Federico ...",La Patagonia rebelde is an Argentinean film ba...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
139,THE BOURNE IDENTITY,2002,118.0,"['action', 'spy', 'thriller']",NaT,Doug Liman,"['Robert Ludlum', 'Tony Gilroy', 'William Blak...","['Matt Damon', 'Franka Potente', 'Chris Cooper']",nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN
162,THE PUNISHER,2004,124.0,"['action', 'crime', 'drama']",NaT,Jonathan Hensleigh,"['Jonathan Hensleigh', 'Michael France']","['Thomas Jane', 'John Travolta', 'Samantha Mat...",An undercover FBI agent becomes a vigilante as...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
173,V FOR VENDETTA,2005,132.0,"['action', 'drama', 'thriller']",NaT,James McTeigue,"['Lilly Wachowski', 'Lana Wachowski']","['Hugo Weaving', 'Natalie Portman', 'Rupert Gr...",nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN
328,UNDERWORLD: BLOOD WARS,2016,91.0,"['action', 'adventure', 'fantasy']",NaT,Anna Foerster,"['Cory Goodman', 'Kyle Ward']","['Kate Beckinsale', 'Theo James', 'Tobias Menz...","Vampire death dealer, Selene (Kate Beckinsale)...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
394,MARY POPPINS RETURNS,2018,145.0,"['family', 'fantasy', 'musical']",NaT,Rob Marshall,"['David Magee', 'P.L. Travers']","['Emily Blunt', 'Meryl Streep', 'Ben Whishaw']",nan,NaN,True,"In Depression-era London, a now-grown Jane and...",2018-12-25,NaN,NaN,NaN
419,TO ALL THE BOYS I'VE LOVED BEFORE,2018,99.0,"['drama', 'romance']",NaT,Susan Johnson,['Jenny Han'],"['Lana Condor', 'John Corbett', 'Noah Centineo']",Lara Jean Song Covey (Lana Condor) writes secr...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
426,YUCATÃ¡N,2018,129.0,nan,NaT,Daniel MonzÃ³n,"['Jorge GuerricaechevarrÃ\xada', 'Daniel MonzÃ...","['Luis Tosar', 'Rodrigo De la Serna', 'Joan Pe...",nan,NaN,False,Two white collar thieves compete fiercely agai...,2018-08-31,"[adventure, comedy]",NaN,NaN

In [32]:
# For this case, there is a value 'nan'
movie_df[movie_df['categories'] == 'nan']

,name,year,runtime,categories,release-date,director,writer,actors,storyline,description,future,plot,released,genre,category,directors
426,YUCATÃ¡N,2018,129.0,nan,NaT,Daniel MonzÃ³n,"['Jorge GuerricaechevarrÃ\xada', 'Daniel MonzÃ...","['Luis Tosar', 'Rodrigo De la Serna', 'Joan Pe...",nan,NaN,False,Two white collar thieves compete fiercely agai...,2018-08-31,"[adventure, comedy]",NaN,NaN
463,CRIP CAMP,2020,106.0,nan,2020-03-26,nan,"['James Lebrecht', 'Nicole Newnham', 'David Ra...","['Larry Allison', 'Dennis Billups', 'William B...","Down the road from Woodstock, a revolution blo...",NaN,NaN,NaN,NaN,NaN,documentary,"[James Lebrecht, Nicole Newnham]"

#### Optional: Dropping Columns

In [33]:
sample = movie_df[['description', 'future', 'plot', 'released', 'genre', 'category', 'directors']]
for x in sample.columns:
    print(f'Column : {x}')
    display(movie_df[movie_df[x].notnull()])

Column : description

,name,year,runtime,categories,release-date,director,writer,actors,storyline,description,future,plot,released,genre,category,directors
51,THE TERMINATOR,1984,107.0,"['action', 'sci-fi']",1984-10-26,James Cameron,"['James Cameron', 'Gale Anne Hurd', 'William W...","['Arnold Schwarzenegger', 'Michael Biehn', 'Li...",nan,A human-looking indestructible cyborg is sent ...,NaN,NaN,NaN,NaN,NaN,NaN
68,HOME ALONE,1990,102.0,"['comedy', 'family']",1990-11-16,Chris Columbus,['John Hughes'],"['Macaulay Culkin', 'Joe Pesci', 'Daniel Stern...",It is Christmas time and the McCallister famil...,An eight-year-old troublemaker must protect hi...,NaN,NaN,NaN,NaN,NaN,NaN
73,MY GIRL,1991,102.0,"['comedy', 'drama', 'romance']",1991-11-27,Howard Zieff,['Laurice Elehwany'],"['Dan Aykroyd', 'Jamie Lee Curtis', 'Macaulay ...",1972. Vada Sultenfuss (played by Anna Chlumsky...,"A young girl, on the threshold of her teen yea...",NaN,NaN,NaN,NaN,NaN,NaN
74,POINT BREAK,1991,122.0,"['action', 'crime', 'thriller']",1991-11-22,Kathryn Bigelow,"['Rick King', 'W. Peter Iliff']","['Patrick Swayze', 'Keanu Reeves', 'Gary Busey...",nan,An F.B.I. Agent goes undercover to catch a gan...,NaN,NaN,NaN,NaN,NaN,NaN
75,TERMINATOR 2: JUDGMENT DAY,1991,137.0,"['action', 'sci-fi', 'thriller']",1991-07-03,James Cameron,"['James Cameron', 'William Wisher Jr.']","['Arnold Schwarzenegger', 'Edward Furlong', 'L...",nan,"A cyborg, identical to the one who failed to k...",NaN,NaN,NaN,NaN,NaN,NaN
78,HOME ALONE 2: LOST IN NEW YORK,1992,120.0,"['comedy', 'family', 'adventure']",1992-11-20,Chris Columbus,['John Hughes'],"['Macaulay Culkin', 'Joe Pesci', 'Daniel Stern...",Kevin McCallister is back. But this time he's ...,One year after Kevin was left home alone and h...,NaN,NaN,NaN,NaN,NaN,NaN
111,THE MATRIX,1999,136.0,"['action', 'fantasy']",1999-03-31,"['Lana Wachowski', 'Lilly Wachowski']","['Lana Wachowski', 'Lilly Wachowski']","['Keanu Reeves', 'Laurence Fishburne', 'Carrie...",nan,Neo (Keanu Reeves) believes that Morpheus (Lau...,NaN,NaN,NaN,NaN,NaN,NaN
147,TERMINATOR 3: RISE OF THE MACHINES,2003,109.0,"['action', 'sci-fi']",2003-07-02,Jonathan Mostow,"['James Cameron', 'Gale Anne Hurd', 'John Bran...","['Arnold Schwarzenegger', 'Nick Stahl', 'Clair...",nan,A cybernetic warrior from a post-apocalyptic f...,NaN,NaN,NaN,NaN,NaN,NaN
149,THE MATRIX RELOADED,2003,138.0,"['sci-fi', 'thriller']",2003-05-15,"['Lana Wachowski', 'Lilly Wachowski']","['Lana Wachowski', 'Lilly Wachowski']","['Ray Anthony', 'Christine Anu', 'Andy Arness'...",nan,"Freedom fighters Neo (Keanu Reeves), Trinity (...",NaN,NaN,NaN,NaN,NaN,NaN
150,THE MATRIX REVOLUTIONS,2003,129.0,"['action', 'thriller']",2003-11-05,"['Lana Wachowski', 'Lilly Wachowski']","['Lana Wachowski', 'Lilly Wachowski']","['Mary Alice', 'Tanveer K. Atwal', 'Helmut Bak...",nan,"In a dystopia overrun by robots, Neo (Keanu Re...",NaN,NaN,NaN,NaN,NaN,NaN
154,50 FIRST DATES,2004,99.0,"['comedy', 'drama', 'romance']",2004-02-13,Peter Segal,['George Wing'],"['Adam Sandler', 'Drew Barrymore', 'Rob Schnei...",nan,Henry Roth is a man afraid of commitment up un...,NaN,NaN,NaN,NaN,NaN,NaN
155,HARRY POTTER AND THE PRISONER OF AZKABAN,2004,142.0,"['adventure', 'family', 'fantasy']",2004-06-04,Alfonso CuarÃ³n,"['Steve Kloves', 'J.K. Rowling']","['Daniel Radcliffe', 'Emma Watson', 'Rupert Gr...",nan,"In Harry Potter and the Prisoner of Azkaban, H...",NaN,NaN,NaN,NaN,NaN,NaN
161,THE PHANTOM OF THE OPERA,2004,143.0,"['drama', 'thriller']",2004-12-10,Joel Schumacher,['Gaston Leroux'],"['Emmy Rossum', 'Gerard Butler', 'Patrick Wils...",nan,"A disfigured musical genius, hidden away in th...",NaN,NaN,NaN,NaN,NaN,NaN
166,HARRY POTTER AND THE GOBLET OF FIRE,2005,157.0,"['adventure', 'family', 'fantasy']",2005-11-18,Mike Newell,"['Steve Kloves', 'J.K. Rowling']","['Daniel Radcliffe', 'Emma Watson', 'Rupert Gr...",nan,When Harry Potter's name emerges from the Gobl...,NaN,NaN,NaN,NaN,NaN,NaN
186,FOOL & FINAL,2007,160.0,"['Indian', 'comedy']",2007-07-01,Ahmed Khan,"['Umesh Shukla', 'Abbas Hirapurwala']","['Sunny Deol', 'Shahid Kapoor', 'Vivek Oberoi'...",nan,"The lives of a career criminal, his girlfriend...",NaN,NaN,NaN,NaN,NaN,NaN
187,HARRY POTTER AND THE ORDER OF THE PHOENIX,2007,138.0,"['adventure', 'family', 'fantasy']",2007-07-11,David Yates,"['Michael Goldenberg', 'J.K. Rowling']","['Daniel Radcliffe', 'Emma Watson', 'Rupert Gr...",nan,"Lord Voldemort has returned, but few want to b...",NaN,NaN,NaN,NaN,NaN,NaN
203,HACHI: A DOG'S TALE,2009,93.0,"['drama', 'family']",2009-06-08,Lasse HallstrÃ¶m,"['Stephen P. Lindsey', 'Kaneto Shindo']","['Richard Gere', 'Joan Allen', 'Sarah Roemer']",nan,"When his master dies, a loyal pooch named Hach...",NaN,NaN,NaN,NaN,NaN,NaN
204,HARRY POTTER AND THE HALF-BLOOD PRINCE,2009,153.0,"['adventure', 'family', 'fantasy']",2009-07-15,David Yates,"['Steve Kloves', 'J.K. Rowling']","['Daniel Radcliffe', 'Emma Watson', 'Rupert Gr...",nan,Voldemort is tightening his grip on both the M...,NaN,NaN,NaN,NaN,NaN,NaN
208,TERMINATOR SALVATION,2009,115.0,"['action', 'adventure', 'sci-fi']",2009-05-21,McG,"['John Brancato', 'Michael Ferris']","['Christian Bale', 'Sam Worthington', 'Moon Bl...",nan,"In 2018, a mysterious new weapon in the war ag...",NaN,NaN,NaN,NaN,NaN,NaN
214,HARRY POTTER AND THE DEATHLY HALLOWS: PART 1,2010,146.0,"['adventure', 'family', 'fantasy']",2010-11-19,David Yates,"['Steve Kloves', 'J.K. Rowling']","['Daniel Radcliffe', 'Emma Watson', 'Rupert Gr...",nan,"Nominated for two Oscars, Harry Potter and the...",NaN,NaN,NaN,NaN,NaN,NaN
216,INCEPTION,2010,148.0,"['adventure', 'action', 'sci-fi', 'thriller']",2010-07-16,Christopher Nolan,['Christopher Nolan'],"['Leonardo DiCaprio', 'Joseph Gordon-Levitt', ...",nan,A thief who steals corporate secrets through t...,NaN,NaN,NaN,NaN,NaN,NaN
218,PERCY JACKSON AND THE OLYMPIANS: THE LIGHTNING...,2010,119.0,"['adventure', 'family', 'fantasy']",2010-02-02,Chris Columbus,"['Craig Titley', 'Rick Riordan']","['Logan Lerman', 'Brandon T. Jackson', 'Alexan...",nan,"Always trouble-prone, the life of teenager Per...",NaN,NaN,NaN,NaN,NaN,NaN
219,RED,2010,111.0,"['comedy', 'action', 'crime']",2010-10-15,Robert Schwentke,"['Jon Hoeber', 'Erich Hoeber']","['Bruce Willis', 'Mary-Louise Parker', 'Morgan...",nan,Retired government agents uncover a plot again...,NaN,NaN,NaN,NaN,NaN,NaN
221,THE BOOK OF ELI,2010,118.0,"['adventure', 'action', 'drama', 'thriller']",2010-03-18,The Hughes Brothers,['Gary Whitta'],"['Denzel Washington', 'Mila Kunis', 'Ray Steve...",nan,"In a violent post-apocalyptic society, a drift...",NaN,NaN,NaN,NaN,NaN,NaN
226,HARRY POTTER AND THE DEATHLY HALLOWS: PART 2,2011,130.0,"['adventure', 'family', 'fantasy']",2011-07-15,David Yates,"['Steve Kloves', 'J.K. Rowling']","['Daniel Radcliffe', 'Emma Watson', 'Rupert Gr...",nan,"In Part 2 of the epic finale, the battle betwe...",NaN,NaN,NaN,NaN,NaN,NaN
294,TERMINATOR GENISYS,2015,126.0,"['action', 'adventure', 'sci-fi']",2009-07-01,Alan Taylor,"['Laeta Kalogridis', 'Patrick Lussier', 'James...","['Arnold Schwarzenegger', 'Jason Clarke', 'Emi...",nan,"When John Connor, leader of the human resistan...",NaN,NaN,NaN,NaN,NaN,NaN

Column : future

,name,year,runtime,categories,release-date,director,writer,actors,storyline,description,future,plot,released,genre,category,directors
339,BLADE RUNNER 2049,2017,0.0,"['sci-fi', 'thriller']",2017-10-05,Denis Villeneuve,"['Hampton Fancher', 'Michael Green', 'Philip K...","['Ryan Gosling', 'Harrison Ford', 'Robin Wrigh...",A young blade runner's discovery of a long-bur...,NaN,true,NaN,NaN,NaN,NaN,NaN
362,THOR: RAGNAROK,2017,137.0,"['action', 'sci-fi', 'fantasy', 'adventure']",2017-10-25,Taika Waititi,"['Christopher Yost', 'Craig Kyle', 'Stephany F...","['Chris Hemsworth', 'Tom Hiddleson', 'Cate Bla...",Thor is imprisoned on the other side of the un...,NaN,False,NaN,NaN,NaN,NaN,NaN
376,BOHEMIAN RHAPSODY,2018,134.0,"['biography', 'drama', 'music']",2018-11-02,Bryan Singer,"['Anthony McCarten', 'Peter Morgan']","['Rami Malek', 'Ben Hardy', 'Gwilym Lee']",A chronicle of the years leading up to Queen's...,NaN,true,NaN,NaN,NaN,NaN,NaN
382,EL ÃNGEL,2018,126.0,"['drama', 'crime']",2018-11-09,Luis Ortega,"['Luis Ortega', 'Rodolfo Palacios']","['Chino DarÃ\xadn', 'Mercedes MorÃ¡n', 'Melena...",The pretty face of Carlos (a 17-year-old teena...,NaN,true,NaN,NaN,NaN,NaN,NaN
394,MARY POPPINS RETURNS,2018,145.0,"['family', 'fantasy', 'musical']",NaT,Rob Marshall,"['David Magee', 'P.L. Travers']","['Emily Blunt', 'Meryl Streep', 'Ben Whishaw']",nan,NaN,True,"In Depression-era London, a now-grown Jane and...",2018-12-25,NaN,NaN,NaN
398,MORTAL ENGINES,2018,125.0,"['fantasy', 'sci-fi']",2018-12-14,Christian Rivers,"['Philip Reeve', 'Peter Jackson ']","['Hugo Weaving', 'Robert Sheehan', 'Stephen La...",nan,NaN,True,"Many years after the ""Sixty Minute War,"" citie...",NaN,NaN,NaN,NaN
400,OVERLORD,2018,NaN,"['Action', 'Horror', 'Mystery']",2018-10-26,Julius Avery,"['Billy Ray', 'Billy Ray']","['Wyatt Russell', 'Pilou AsbÃ¦k', 'Bokeem Wood...",nan,NaN,True,"On the eve of D-Day, American paratroopers are...",NaN,NaN,NaN,NaN
403,PETTA,2018,120.0,"['action', 'adventure']",2018-12-12,Karthik Subbaraj,['Karthik Subbaraj'],"['Rajinikanth', 'Vijay Sethupathi', 'Trisha']",Bashaa Returns,NaN,true,NaN,NaN,NaN,NaN,NaN
404,RALPH BREAKS THE INTERNET,2018,142.0,"['Animation', 'Adventure', 'Comedy']",2018-11-21,Phil Johnston,"['Phil Johnston', 'Pamela Ribon']","['Sarah Silverman', 'Alan Tudyk', 'James Corden']",nan,NaN,True,Wreck-It Ralph wrecks the internet.,NaN,NaN,NaN,NaN
424,VICE,2018,124.0,"['Biography', 'Drama']",2018-12-21,Adam McKay,['Adam McKay'],"['Christian Bale', 'Amy Adams', 'Steve Carell']",nan,NaN,True,The story of former U.S. Vice President Dick C...,NaN,NaN,NaN,NaN
426,YUCATÃ¡N,2018,129.0,nan,NaT,Daniel MonzÃ³n,"['Jorge GuerricaechevarrÃ\xada', 'Daniel MonzÃ...","['Luis Tosar', 'Rodrigo De la Serna', 'Joan Pe...",nan,NaN,False,Two white collar thieves compete fiercely agai...,2018-08-31,"[adventure, comedy]",NaN,NaN

Column : plot

,name,year,runtime,categories,release-date,director,writer,actors,storyline,description,future,plot,released,genre,category,directors
394,MARY POPPINS RETURNS,2018,145.0,"['family', 'fantasy', 'musical']",NaT,Rob Marshall,"['David Magee', 'P.L. Travers']","['Emily Blunt', 'Meryl Streep', 'Ben Whishaw']",nan,NaN,True,"In Depression-era London, a now-grown Jane and...",2018-12-25,NaN,NaN,NaN
398,MORTAL ENGINES,2018,125.0,"['fantasy', 'sci-fi']",2018-12-14,Christian Rivers,"['Philip Reeve', 'Peter Jackson ']","['Hugo Weaving', 'Robert Sheehan', 'Stephen La...",nan,NaN,True,"Many years after the ""Sixty Minute War,"" citie...",NaN,NaN,NaN,NaN
400,OVERLORD,2018,NaN,"['Action', 'Horror', 'Mystery']",2018-10-26,Julius Avery,"['Billy Ray', 'Billy Ray']","['Wyatt Russell', 'Pilou AsbÃ¦k', 'Bokeem Wood...",nan,NaN,True,"On the eve of D-Day, American paratroopers are...",NaN,NaN,NaN,NaN
404,RALPH BREAKS THE INTERNET,2018,142.0,"['Animation', 'Adventure', 'Comedy']",2018-11-21,Phil Johnston,"['Phil Johnston', 'Pamela Ribon']","['Sarah Silverman', 'Alan Tudyk', 'James Corden']",nan,NaN,True,Wreck-It Ralph wrecks the internet.,NaN,NaN,NaN,NaN
424,VICE,2018,124.0,"['Biography', 'Drama']",2018-12-21,Adam McKay,['Adam McKay'],"['Christian Bale', 'Amy Adams', 'Steve Carell']",nan,NaN,True,The story of former U.S. Vice President Dick C...,NaN,NaN,NaN,NaN
426,YUCATÃ¡N,2018,129.0,nan,NaT,Daniel MonzÃ³n,"['Jorge GuerricaechevarrÃ\xada', 'Daniel MonzÃ...","['Luis Tosar', 'Rodrigo De la Serna', 'Joan Pe...",nan,NaN,False,Two white collar thieves compete fiercely agai...,2018-08-31,"[adventure, comedy]",NaN,NaN

Column : released

,name,year,runtime,categories,release-date,director,writer,actors,storyline,description,future,plot,released,genre,category,directors
394,MARY POPPINS RETURNS,2018,145.0,"['family', 'fantasy', 'musical']",NaT,Rob Marshall,"['David Magee', 'P.L. Travers']","['Emily Blunt', 'Meryl Streep', 'Ben Whishaw']",nan,NaN,True,"In Depression-era London, a now-grown Jane and...",2018-12-25,NaN,NaN,NaN
426,YUCATÃ¡N,2018,129.0,nan,NaT,Daniel MonzÃ³n,"['Jorge GuerricaechevarrÃ\xada', 'Daniel MonzÃ...","['Luis Tosar', 'Rodrigo De la Serna', 'Joan Pe...",nan,NaN,False,Two white collar thieves compete fiercely agai...,2018-08-31,"[adventure, comedy]",NaN,NaN

Column : genre

,name,year,runtime,categories,release-date,director,writer,actors,storyline,description,future,plot,released,genre,category,directors
426,YUCATÃ¡N,2018,129.0,nan,NaT,Daniel MonzÃ³n,"['Jorge GuerricaechevarrÃ\xada', 'Daniel MonzÃ...","['Luis Tosar', 'Rodrigo De la Serna', 'Joan Pe...",nan,NaN,False,Two white collar thieves compete fiercely agai...,2018-08-31,"[adventure, comedy]",NaN,NaN

Column : category

,name,year,runtime,categories,release-date,director,writer,actors,storyline,description,future,plot,released,genre,category,directors
463,CRIP CAMP,2020,106.0,nan,2020-03-26,nan,"['James Lebrecht', 'Nicole Newnham', 'David Ra...","['Larry Allison', 'Dennis Billups', 'William B...","Down the road from Woodstock, a revolution blo...",NaN,NaN,NaN,NaN,NaN,documentary,"[James Lebrecht, Nicole Newnham]"

Column : directors

,name,year,runtime,categories,release-date,director,writer,actors,storyline,description,future,plot,released,genre,category,directors
463,CRIP CAMP,2020,106.0,nan,2020-03-26,nan,"['James Lebrecht', 'Nicole Newnham', 'David Ra...","['Larry Allison', 'Dennis Billups', 'William B...","Down the road from Woodstock, a revolution blo...",NaN,NaN,NaN,NaN,NaN,documentary,"[James Lebrecht, Nicole Newnham]"

In [34]:
movie_df.drop(columns=['description', 'future', 'plot','released', 'genre', 'category', 'directors'], axis=1, inplace=True)

### Remove Punctuations, Numbers, and Symbols

In [35]:
def rem_punct(my_str):
    if my_str is None:
        return None
    
    punctuations = '''!¡()-[]{};:'.'"“”`\,.<>/|?@#$%^—-=&_+0123456789•~*…''' 

    no_punct = ""
    for char in my_str:
        if char not in punctuations:
            no_punct += char
    return no_punct

In [36]:
movie_df['categories'] = movie_df['categories'].apply(rem_punct)
movie_df['categories'] = movie_df['categories'].apply(lambda row: ", ".join(row.split(' ')) if isinstance(row, str) else '')

In [37]:
movie_df

,name,year,runtime,categories,release-date,director,writer,actors,storyline
0,THE WIZARD OF OZ,1925,81.0,"comedy, family, fantasy",1925-01-27,Larry Semon,"['L. Frank Baum', 'Frank Joslyn Baum', 'Edgar ...","['Dorothy Dwan', 'Mary Carr', 'Virginia Pearso...","Dorothy, heir to the Oz throne, must take it b..."
1,FRANKENSTEIN,1931,70.0,"drama, horror, scifi",1931-09-21,James Whale,"['John L. Balderston', 'Mary Shelley']","['Colin Clive', 'Mae Clarke', 'John Boles', 'B...",Henry Frankenstein is a doctor who is trying t...
2,KING KONG,1933,100.0,"adventure, horror, scifi",1933-04-07,"['Merian C. Cooper', 'Ernest B. Schoedsack']","['James Ashmore Creelman', 'Ruth Rose', 'Meria...","['Fay Wray', 'Robert Armstrong', 'Bruce Cabot'...",A film crew goes to a tropical island for an e...
3,THE INVISIBLE MAN,1933,71.0,"horror, scifi",1933-11-03,James Whale,"['H.G. Wells', 'R.C. Sherriff']","['Claude Rains', 'William Harrigan', 'Gloria S...","A stranger, his face covered in bandages takes..."
4,THE ADVENTURES OF ROBIN HOOD,1938,102.0,"action, adventure, romance",1938-05-14,"['Michael Curtiz', 'William Keighley']","['Norman Reilly Raine', 'Seton I. Miller']","['Errol Flynn', 'Olivia de Havilland', 'Basil ...",When Prince John and the Norman Lords begin op...
...,...,...,...,...,...,...,...,...,...
467,THE INVISIBLE MAN,2020,124.0,"horror, thriller, scifi",2020-02-28,Leigh Whannell,['Leigh Whannell'],"['Elisabeth Moss', 'Aldis Hodge', 'Storm Reid'...",It follows a woman who believes she is being s...
468,BLACK WIDOW,2021,134.0,"scifi, action, adventure",2021-07-09,['Cate Shortland'],['Eric Pearson'],"['Scarlett Johansson', 'Florence Pugh', 'Rache...","Natasha Romanoff, aka Black Widow, confronts t..."
469,CRUELLA,2021,134.0,"adventure, comedie, crime",2021-05-18,['Craig Gillespie'],"['Dana Fox', 'Tony McNamara']","['Emma Stone', 'Emma Thompson', 'Joel Fry', 'P...",Estella is a young and clever grifter who's de...
470,ETERNALS,2021,157.0,"drama, adventure, action",2021-10-18,Chloe Zhao,"['Chloe Zhao', 'Patrick Burleigh', 'Ryan Firpo...","['Gemma Chan', 'Richard Madden', 'ThÃ©odore Pe...","The saga of the Eternals, a race of immortal b..."
471,RAYA AND THE LAST DRAGON,2021,124.0,"animation, action, adventure",2021-03-04,"['Don Hall', 'Carlos LÃ³pez Estrada']","['Qui Nguyen', 'Adele Lim']","['Kelly Marie Tran', 'Awkwafina', 'Izaac Wang'...","Long ago, in the fantasy world of Kumandra, hu..."

### Special Characters

In [38]:
def latin_char(name):
    if isinstance(name, str):
        normalized_text = unicodedata.normalize('NFKD', name)
        encoded_text = normalized_text.encode('ASCII', 'ignore')
        cleaned_name = encoded_text.decode('utf-8')
        return cleaned_name
    else:
        return name

In [39]:
movie_df['name'] = movie_df.name.apply(latin_char)

In [40]:
movie_df.iloc[426]

name                                                      YUCATAN
year                                                         2018
runtime                                                     129.0
categories                                                    nan
release-date                                                  NaT
director                                           Daniel MonzÃ³n
writer          ['Jorge GuerricaechevarrÃ\xada', 'Daniel MonzÃ...
actors          ['Luis Tosar', 'Rodrigo De la Serna', 'Joan Pe...
storyline                                                     nan
Name: 426, dtype: object

### Check for Duplicates

In [41]:
dup_movies = movie_df[movie_df.duplicated(subset=['name'], keep=False)].sort_values('name')
dup_movies

,name,year,runtime,categories,release-date,director,writer,actors,storyline
343,GHOST IN THE SHELL,2017,107.0,"action, crime, drama",2017-03-31,Rupert Sanders,"['Shirow Masamune', 'Jamie Moss', 'William Whe...","['Scarlett Johansson', 'Pilou AsbÃ¦k', 'Takesh...","In the near future, Major is the first of her ..."
93,GHOST IN THE SHELL,1995,85.0,"animation, drama, fantasy",1995-11-18,Mamoru Oshii,"['Shirow Masamune', 'Kazunori ItÃ´']","['Atsuko Tanaka', 'Iemasa Kayumi', 'Akio Ã\x94...",A cyborg policewoman and her partner hunt a my...
442,HOBBS & SHAW,2019,136.0,"action, adventure",2019-08-02,David Leitch,"['Jennifer Lee', 'Drew Pearce']","['Dwayne Johnson', 'Jason Statham', 'Idris Elb...",The plot follows the unlikely team-up of the ...
441,HOBBS & SHAW,2019,136.0,action,2019-07-13,David Leitch,"['Chris Morgan', 'Drew Pearce']","['Dwayne Johnson', 'Jason Statham', 'Idris Elb...",Brixton Lorr is a cybernetically enhanced sold...
2,KING KONG,1933,100.0,"adventure, horror, scifi",1933-04-07,"['Merian C. Cooper', 'Ernest B. Schoedsack']","['James Ashmore Creelman', 'Ruth Rose', 'Meria...","['Fay Wray', 'Robert Armstrong', 'Bruce Cabot'...",A film crew goes to a tropical island for an e...
167,KING KONG,2005,187.0,"drama, fantasy, action, adventure, romance",2005-12-05,Peter Jackson,"['Fran Walsh', 'Philippa Boyens', 'Peter Jacks...","['Naomi Watts', 'Jack Black', 'Peter Jackson',...",Filmmaker Carl Denham and his crew encounter a...
145,OLDBOY,2003,101.0,"action, drama, mystery",2003-10-15,Chan-wook Park,Garon Tsuchiya,"['Min-sik Choi', 'Ji-tae Yu', 'Hye-jeong Kang']",After being kidnapped and imprisoned for fifte...
253,OLDBOY,2013,104.0,"action, drama, mystery",2013-11-27,Spike Lee,Garon Tsuchiya,"['Josh Brolin', 'Elizabeth Olsen', 'Samuel L. ...",After being kidnapped and imprisoned for twent...
359,THE INVISIBLE MAN,2017,88.0,scifi,2018-02-08,Khian Bartlett,['Joseph Henson'],"['Rene Abelar', 'Zachary Bray', 'Chris Coon', ...",A modern retelling of H.G. Wells classic novel...
467,THE INVISIBLE MAN,2020,124.0,"horror, thriller, scifi",2020-02-28,Leigh Whannell,['Leigh Whannell'],"['Elisabeth Moss', 'Aldis Hodge', 'Storm Reid'...",It follows a woman who believes she is being s...
3,THE INVISIBLE MAN,1933,71.0,"horror, scifi",1933-11-03,James Whale,"['H.G. Wells', 'R.C. Sherriff']","['Claude Rains', 'William Harrigan', 'Gloria S...","A stranger, his face covered in bandages takes..."
90,THE LION KING,1994,88.0,"animated, musical",1994-06-15,"['Roger Allers', 'Rob Minkoff']","['Linda Woolverton', 'Irene Mecchi', 'Jonathan...","['Matthew Broderick', 'James Earl Jones', 'Jer...","The Lion King tells the story of Simba, a youn..."
457,THE LION KING,2019,118.0,"animation, adventure, drama, family, musical",2019-07-19,Jon Favreau,"['Jeff Nathanson', 'Brenda Chapman', 'Irene Me...","['Donald Glover', 'Seth Rogen', 'Chiwetel Ejio...","After the murder of his father, a young lion p..."
132,THE LOST WORLD: JURASSIC PARK,2001,92.0,"adventure, action, scifi, thriller",2001-07-18,Joe Johnston,"['Michael Crichton', 'Peter Buchman', 'Alexand...","['Sam Neill', 'William H. Macy', 'TÃ©a Leoni']",Dr. Alan Grant is now a happy man with the pre...
105,THE LOST WORLD: JURASSIC PARK,1997,129.0,"adventure, action, scifi",1997-05-23,Steven Spielberg,"['Michael Crichton', 'David Koepp']","['Jeff Goldblum', 'Julianne Moore', 'Pete Post...",Four years after the failure of Jurassic Park ...
162,THE PUNISHER,2004,124.0,"action, crime, drama",NaT,Jonathan Hensleigh,"['Jonathan Hensleigh', 'Michael France']","['Thomas Jane', 'John Travolta', 'Samantha Mat...",An undercover FBI agent becomes a vigilante as...
66,THE PUNISHER,1989,89.0,"action, crime, drama, thriller",1989-10-05,Mark Goldblatt,Boaz Yakin,"['Dolph Lundgren', 'Louis Gossett Jr.', 'Jeroe...",When Frank Castle's family is murdered by crim...
5,THE WIZARD OF OZ,1939,110.0,"musical, scifi, fantasy, adventure",1939-08-25,"['King Vidor', 'Victor Fleming']","['Florence Ryerson', 'Noel Langley', 'Edgar Al...","['Judy Garland', 'Ray Bolger', 'Jack Haley', '...",In this charming film based on the popular L. ...
0,THE WIZARD OF OZ,1925,81.0,"comedy, family, fantasy",1925-01-27,Larry Semon,"['L. Frank Baum', 'Frank Joslyn Baum', 'Edgar ...","['Dorothy Dwan', 'Mary Carr', 'Virginia Pearso...","Dorothy, heir to the Oz throne, must take it b..."

In [42]:
dup_movies_year = movie_df[movie_df.duplicated(subset=['name', 'year'], keep=False)]#.sort_values('name')
dup_movies_year

,name,year,runtime,categories,release-date,director,writer,actors,storyline
441,HOBBS & SHAW,2019,136.0,action,2019-07-13,David Leitch,"['Chris Morgan', 'Drew Pearce']","['Dwayne Johnson', 'Jason Statham', 'Idris Elb...",Brixton Lorr is a cybernetically enhanced sold...
442,HOBBS & SHAW,2019,136.0,"action, adventure",2019-08-02,David Leitch,"['Jennifer Lee', 'Drew Pearce']","['Dwayne Johnson', 'Jason Statham', 'Idris Elb...",The plot follows the unlikely team-up of the ...

`dup_movies_year` has some discrepencies, having the same movie title and released at the same year but their release date are different.

#### Drop Duplicates

In [43]:
movie_df_new = movie_df.drop_duplicates(subset=['name', 'year'], keep='last')
movie_df_new

,name,year,runtime,categories,release-date,director,writer,actors,storyline
0,THE WIZARD OF OZ,1925,81.0,"comedy, family, fantasy",1925-01-27,Larry Semon,"['L. Frank Baum', 'Frank Joslyn Baum', 'Edgar ...","['Dorothy Dwan', 'Mary Carr', 'Virginia Pearso...","Dorothy, heir to the Oz throne, must take it b..."
1,FRANKENSTEIN,1931,70.0,"drama, horror, scifi",1931-09-21,James Whale,"['John L. Balderston', 'Mary Shelley']","['Colin Clive', 'Mae Clarke', 'John Boles', 'B...",Henry Frankenstein is a doctor who is trying t...
2,KING KONG,1933,100.0,"adventure, horror, scifi",1933-04-07,"['Merian C. Cooper', 'Ernest B. Schoedsack']","['James Ashmore Creelman', 'Ruth Rose', 'Meria...","['Fay Wray', 'Robert Armstrong', 'Bruce Cabot'...",A film crew goes to a tropical island for an e...
3,THE INVISIBLE MAN,1933,71.0,"horror, scifi",1933-11-03,James Whale,"['H.G. Wells', 'R.C. Sherriff']","['Claude Rains', 'William Harrigan', 'Gloria S...","A stranger, his face covered in bandages takes..."
4,THE ADVENTURES OF ROBIN HOOD,1938,102.0,"action, adventure, romance",1938-05-14,"['Michael Curtiz', 'William Keighley']","['Norman Reilly Raine', 'Seton I. Miller']","['Errol Flynn', 'Olivia de Havilland', 'Basil ...",When Prince John and the Norman Lords begin op...
...,...,...,...,...,...,...,...,...,...
467,THE INVISIBLE MAN,2020,124.0,"horror, thriller, scifi",2020-02-28,Leigh Whannell,['Leigh Whannell'],"['Elisabeth Moss', 'Aldis Hodge', 'Storm Reid'...",It follows a woman who believes she is being s...
468,BLACK WIDOW,2021,134.0,"scifi, action, adventure",2021-07-09,['Cate Shortland'],['Eric Pearson'],"['Scarlett Johansson', 'Florence Pugh', 'Rache...","Natasha Romanoff, aka Black Widow, confronts t..."
469,CRUELLA,2021,134.0,"adventure, comedie, crime",2021-05-18,['Craig Gillespie'],"['Dana Fox', 'Tony McNamara']","['Emma Stone', 'Emma Thompson', 'Joel Fry', 'P...",Estella is a young and clever grifter who's de...
470,ETERNALS,2021,157.0,"drama, adventure, action",2021-10-18,Chloe Zhao,"['Chloe Zhao', 'Patrick Burleigh', 'Ryan Firpo...","['Gemma Chan', 'Richard Madden', 'ThÃ©odore Pe...","The saga of the Eternals, a race of immortal b..."
471,RAYA AND THE LAST DRAGON,2021,124.0,"animation, action, adventure",2021-03-04,"['Don Hall', 'Carlos LÃ³pez Estrada']","['Qui Nguyen', 'Adele Lim']","['Kelly Marie Tran', 'Awkwafina', 'Izaac Wang'...","Long ago, in the fantasy world of Kumandra, hu..."

In [44]:
# ------- or you can use the parameter 'inplace' in drop_duplicates() ------- #
# ---------------- to overwrite directly the main dataframe ----------------- #

movie_df.drop_duplicates(subset=['name', 'year'], keep='last', inplace=True)

In [45]:
movie_df

,name,year,runtime,categories,release-date,director,writer,actors,storyline
0,THE WIZARD OF OZ,1925,81.0,"comedy, family, fantasy",1925-01-27,Larry Semon,"['L. Frank Baum', 'Frank Joslyn Baum', 'Edgar ...","['Dorothy Dwan', 'Mary Carr', 'Virginia Pearso...","Dorothy, heir to the Oz throne, must take it b..."
1,FRANKENSTEIN,1931,70.0,"drama, horror, scifi",1931-09-21,James Whale,"['John L. Balderston', 'Mary Shelley']","['Colin Clive', 'Mae Clarke', 'John Boles', 'B...",Henry Frankenstein is a doctor who is trying t...
2,KING KONG,1933,100.0,"adventure, horror, scifi",1933-04-07,"['Merian C. Cooper', 'Ernest B. Schoedsack']","['James Ashmore Creelman', 'Ruth Rose', 'Meria...","['Fay Wray', 'Robert Armstrong', 'Bruce Cabot'...",A film crew goes to a tropical island for an e...
3,THE INVISIBLE MAN,1933,71.0,"horror, scifi",1933-11-03,James Whale,"['H.G. Wells', 'R.C. Sherriff']","['Claude Rains', 'William Harrigan', 'Gloria S...","A stranger, his face covered in bandages takes..."
4,THE ADVENTURES OF ROBIN HOOD,1938,102.0,"action, adventure, romance",1938-05-14,"['Michael Curtiz', 'William Keighley']","['Norman Reilly Raine', 'Seton I. Miller']","['Errol Flynn', 'Olivia de Havilland', 'Basil ...",When Prince John and the Norman Lords begin op...
...,...,...,...,...,...,...,...,...,...
467,THE INVISIBLE MAN,2020,124.0,"horror, thriller, scifi",2020-02-28,Leigh Whannell,['Leigh Whannell'],"['Elisabeth Moss', 'Aldis Hodge', 'Storm Reid'...",It follows a woman who believes she is being s...
468,BLACK WIDOW,2021,134.0,"scifi, action, adventure",2021-07-09,['Cate Shortland'],['Eric Pearson'],"['Scarlett Johansson', 'Florence Pugh', 'Rache...","Natasha Romanoff, aka Black Widow, confronts t..."
469,CRUELLA,2021,134.0,"adventure, comedie, crime",2021-05-18,['Craig Gillespie'],"['Dana Fox', 'Tony McNamara']","['Emma Stone', 'Emma Thompson', 'Joel Fry', 'P...",Estella is a young and clever grifter who's de...
470,ETERNALS,2021,157.0,"drama, adventure, action",2021-10-18,Chloe Zhao,"['Chloe Zhao', 'Patrick Burleigh', 'Ryan Firpo...","['Gemma Chan', 'Richard Madden', 'ThÃ©odore Pe...","The saga of the Eternals, a race of immortal b..."
471,RAYA AND THE LAST DRAGON,2021,124.0,"animation, action, adventure",2021-03-04,"['Don Hall', 'Carlos LÃ³pez Estrada']","['Qui Nguyen', 'Adele Lim']","['Kelly Marie Tran', 'Awkwafina', 'Izaac Wang'...","Long ago, in the fantasy world of Kumandra, hu..."

## Another Example!
<font size='3px'><b>Let's test this on a pdf dataset</b></font>

### PDF Dataset

In [46]:
with pdfplumber.open("./Datasets/sampledata_PDF.pdf") as pdf:
    tb = []
    for i in tqdm(range(len(pdf.pages))):
        page = ' '.join(pdf.pages[i].extract_text().split('\n')[1:-1])
        tb.append(page)

  0%|          | 0/7 [00:00<?, ?it/s]

In [47]:
pdf_ = [text for text in tb if text]
pdf_ = str(pdf_)[1:-1]
pdf_

"'humanitarians are increasingly having to incorporate climate data and forecasts into their analysis and planning. This guidance series has been developed to help humanitarians to access, analyze and interpret common types of climate and weather data, and to provide a common language for working with meteorological and hydrological services. Key takeaways • Observational rainfall data such as CHIRPS or ARC2 captures how much rain has fallen over a defined period of time. • The rainfall is measured at weather stations or estimated through satellite or radar imagery. • The data can be presented as the total amount of rainfall observed over the period of time, or as below, at or above normal conditions. • Datasets that combine station data and satellite or radar imagery are the recommended source of data for humanitarian purposes. • Observational rainfall data can be analyzed to answer a range of questions, such as: • What areas are currently affected by drought, and how severely? • What was the duration of the longest dry spell during the past rainy season? • How many days of heavy rainfall were there in the week leading up to the floods? • Which area received the most rain last month? • How often does an area experience dry spells? • How does this year’s rainfall compare to previous years? What is observational rainfall data? Observational rainfall data captures how much rain fell over a defined period of time, ranging from an hour to a day. This data can then be used to calculate the total rainfall for different time periods, such as 5 days (pentad), 10 days (dekad), a week, a month or a season. Observational rainfall datasets can go back decades and have broad geographic coverage, enabling historical trend analysis and comparisons. Observational rainfall data is produced by measuring the amount of rainfall at precise locations, which are called measuring stations or gauges (e.g., the stars in Figure 1 below). Station data is typically obtained from national or regional meteorological services and should only be used in accordance with their guidance. Some of the advantages of station data are that it is accurate at the specific locations, it is collected frequently and it has been collected over the long-term, allowing for trend analysis. On the other hand, station data is only available for specific locations and is subject to bias due to wind, evaporation, and changes in measurement devices. Contact the local or regional meteorological services to learn whether station data is available, where the stations are located, how often the data is updated, and whether historical records are available.', 'kilometers wide (e.g., the squares in Figure 1 below). Satellite imagery is typically obtained by global providers and academic or research centers (e.g., the Climate Hazards Center) who share their derived estimates publicly. Satellite or radar images are useful for understanding patterns over larger geographic areas. Some of the advantages of satellite data are that it has extensive geographic coverage, including in remote and inaccessible areas, and that it is shared in a continuous and consistent way. On the other hand, satellite measurements are subject to errors due to cloud contamination, and the data has a shorter historical record. Figure 1. Weather Stations in Zambia (red stars). The grid superimposed onto the map consists of individual boxes, each of which corresponds to a particular location where satellite weather measurements are conducted by certain providers. In this case, the grid is the one used by the ARC2 dataset (see below). The size of each box is 0.1 degree (about 11 km at the equator). In order to help correct for the inaccuracies and errors that are present in the two types of data and take advantage of their individual strengths, research institutions have produced rainfall datasets that combine station and satellite/radar observations. Datasets that combine these observations are the recommended source of data for humanitarian purposes. Observational precipitation data can be presented in various formats, each providing unique insights into precipitation patterns. The most common representation is through absolute values, which reflect the actual amount of precipitation observed at a specific location and time, typically measured in millimeters. Precipitation averages, which are calculated from historical records over a period of typically at least 10 years, can be produced for a specific location, season, or year. A precipitation anomaly represents the deviation from the expected or average precipitation over a particular period, which can be expressed as a difference in millimeters or as a percentage. The purpose of the analysis determines the most useful representation. Absolute values provide insight into the total precipitation received at a location, while anomalies and averages help to understand long-term trends, including dry or wet periods, which is valuable for assessing drought or excessive rainfall conditions severity.', 'Among the many sources of data available, we introduce here two common sources of observational rainfall data, both of which combine station and satellite data: CHIRPS and ARC2. CHIRPS refers to the Climate Hazards Group InfraRed Precipitation with Station data and is produced by scientists from the US Geological Survey and the Climate Hazards Center at the University of Santa Barbara. ARC2 refers to Africa Rainfall Climatology Version 2 and it is produced by The National Oceanic and Atmospheric Administration’s Climate Prediction Center for the Famine Early Warning System. You can access the data directly from these providers, or use the tabular CHIRPS datasets that provides pre-computed rainfall metrics at admin2 and is available on HDX.1 COMPARISON OF CHIRPS AND ARC2 OBSERVATIONAL RAINFALL DATA Source CHIRPS ARC2 Format Raster Raster Geographical coverage Global (quasi2) Africa Spatial granularity 0.05 degree (5.5 km at the equator) 0.1 degree (11 km at the equator) (also referred to as spatial resolution) Temporal granularity Daily rainfall3 Daily rainfall (aso referred to as temporal resolution) Historical coverage 1981 - today 1983 - today Publication Every month, around the third week of Every day, with a 2-day lag the following month Most common uses • Monthly, seasonal, or yearly rainfall • Near real-time monitoring in Africa monitoring • Year-to-year comparisons in Africa • Included in other tools including those used for drought monitoring and FEWS NET assessments • Trend analysis across years Questions to answer with observational rainfall data Observational rainfall data can be used to answer a number of questions and inform decision making in humanitarian operations. Examples include: • How much rain fell in the past x days/weeks/months? Observational rainfall datasets provide data on the total amount of rainfall for an area over a discrete period of time, which can be aggregated and used to calculate rainfall over different time intervals. 1 https://data.humdata.org/organization/wfp?q=chirps 2 The dataset spans the latitude range 50°S-50°N, and all longitudes. 3 CHIRPS produces a preliminary version of their estimates with a latency of two days. The final version is published in the third week of the following month.', 'rainfall data goes back decades and can therefore be used to determine whether rainfall for a month or a season is above, at or below the historical average. • Were there more rainy days this month than last month? Observational rainfall data is available for each day and can be used to determine if it rained or not on a given day and to count the number of dry or wet days during a specific period of time. • How many dry spells were there during the past rainy season? How long was the longest dry spell and the heaviest rain streak this past rainy season? Observational rainfall data can be used to detect the occurrence, location and duration of dry spells and prolonged periods of heavy rain. • How often in the past decade were more than x millimeters of rainfall measured? Observational rainfall data provides daily rainfall totals in millimeters and can be used to assess how often an area received rain above or below a given threshold. • Which region received the most rain last month? Observational rainfall data can be aggregated to provide rainfall totals for larger geographic areas and then used to compare rain for that area. Observational rainfall data cannot answer the following questions: • How much will it rain during a period of time in the future? Observational rainfall data is referred to as observational because it describes what happened in the past. It does not tell you anything about future rainfall. • Is a severe flooding event about to occur? Are we going through a severe drought? Observational rainfall data does not provide sufficient information to inform you about the risk of flooding in the near future or how severe a drought is likely to be. This is because floods and droughts are complex phenomena caused by several interacting factors and they cannot be explained exclusively by the amount of precipitation. • How much rainfall from a given period of time in the past was due to specific tropical storm or typhoon? It is hard to differentiate between the amount of rain caused by average atmospheric conditions and the amount of rain induced by a specific atmospheric phenomenon. As a result, using observational rainfall data alone, it is not possible to say how much rainfall is due strictly to a tropical storm or typhoon. More data is needed to infer the origin of a heavy rainfall event.', 'Once you have identified how you want to use the data, it is important to bear in mind some common limitations when conducting your analysis. 1. Low-amount or short-duration rainfall may be underreported in certain geographical terrains or during extreme precipitation events.4 Gauges are constantly being improved to reduce error and datasets that combine station and satellite/radar data are best at correcting for these limitations. However, it is still important to keep these limitations in mind, especially when doing analysis that is looking at meteorological events that involve low-amount or short-duration rainfall, such as dry spells. 2. There are fewer gauge stations in rural areas and certain developing countries, which means that observational rainfall data is often less accurate in these locations. Fewer gauge stations means that there are fewer measurements for that geographic area, resulting in a less complete picture of what is happening on the ground. Differences in the amount of rainfall received in two locations might be missed if there are not stations to capture rainfall in both locations.5 3. Observational rainfall data is usually provided as a raster dataset, where the geographic area is represented by a contiguous grid of cells, or pixels. Each cell represents a discrete area of land, and has a value associated with it but the cells do not neatly fit within administrative boundaries. Calculating rainfall for an administrative area requires an aggregation. The choice of the aggregation method (average, maximum, total etc.) as well as the choice of which cells to include within a given administrative division (all cells fully included, or all cells touched etc.) will impact the results. This is especially true for lower administrative divisions. As a result, adding together the total rainfall for all the districts in a region may not equal the total rainfall calculated for the region. 4. If using station data, it is important to bear in mind that stations are easily subject to deterioration and require frequent maintenance, which may affect their accuracy. For this reason, calculating temporal averages, anomalies or trends over long periods of time should be performed with care. When possible, verify with the provider the adequacy of the measurements over long periods of time. This limitation does not apply to CHIRPS and ARC2 datasets, which have been calibrated and combined with satellite observations by climate institutions. 5. For station data, differences exist between measuring instruments and quality of their measurements. This may heavily affect comparisons between different locations. Therefore, when performing geographical averages, it is preferable to use radar data, satellite data or observational datasets already calibrated by institutions or universities such as CHIRPS or ARC2. 4 Learn more: https://www.chc.ucsb.edu/data/chirps 5 Learn more here: https://wiki.chc.ucsb.edu/CHIRPS_FAQ#What_is_the_spatial_density_of_station_data_used_in_CHIRPS.3F', '• Learn more about the CHIRPS6 and ARC27 observational datasets and/or download data directly from the providers. • CHIRPS on HDX8: Download pre-computed tabular data (CSV format) on precipitation totals, averages, anomalies per administrative region. • ARC29: Download 1-month or 10-day cumulative precipitation totals (raster, tabular, image data). • OCHA AnticiPy10: Download raster (NetCDF) data directly from CHIRPS and ARC2 using a Python library. This guidance was developed by the OCHA Centre for Humanitarian Data11 with input from Columbia University Climate School12 International Research Institute for Climate and Society13, the Royal Netherlands Meteorological Institute14, and the Earth Observation Unit of the Research, Assessment and Monitoring division of the World Food Programme. 6 https://www.chc.ucsb.edu/data/chirps 7 https://www.icpac.net/data-center/arc2/ 8 https://data.humdata.org/dataset?q=CHIRPS 9 https://gmes.icpac.net/data-center/arc2-rfe 10 https://github.com/OCHA-DAP/ocha-anticipy 11 https://centre.humdata.org/ 12 https://www.climate.columbia.edu/ 13 https://iri.columbia.edu/ 14 https://www.knmi.nl/over-het-knmi/about'"

### Remove Punctuation

In [48]:
def rem_punct(my_str):
    
    if my_str is None:
        return None
    
    punctuations = '''!¡()-[]{};:''"“”`\,<>/|?@#$%^—-=&_+0123456789•~*…''' 

    no_punct = ""
    for char in my_str:
        if char not in punctuations:
            no_punct += char
    return no_punct

### Tokenization

In [49]:
def sent_tokenize(text):
    word_tokens = nltk.sent_tokenize(text)
    return word_tokens

def word_tokenize(text):
    word_tokens = nltk.word_tokenize(text)
    return word_tokens

In [51]:
pdf_ = rem_punct(pdf_)
pdf_sent = sent_tokenize(pdf_)[0:3]
pdf_sent

['humanitarians are increasingly having to incorporate climate data and forecasts into their analysis and planning.',
 'This guidance series has been developed to help humanitarians to access analyze and interpret common types of climate and weather data and to provide a common language for working with meteorological and hydrological services.',
 'Key takeaways  Observational rainfall data such as CHIRPS or ARC captures how much rain has fallen over a defined period of time.']

### Word Contraction

In [52]:
import contractions

pdf_contra=[]
for sent in pdf_sent:
    rempunct = rem_punct(sent)
    contra = contractions.fix(rempunct)
    token = word_tokenize(contra)[:-1]
    pdf_contra.append(' '.join(token))
    
pdf_contra

['humanitarians are increasingly having to incorporate climate data and forecasts into their analysis and planning',
 'This guidance series has been developed to help humanitarians to access analyze and interpret common types of climate and weather data and to provide a common language for working with meteorological and hydrological services',
 'Key takeaways Observational rainfall data such as CHIRPS or ARC captures how much rain has fallen over a defined period of time']

### Remove Stop words

In [53]:
from nltk.corpus import stopwords

def remove_stopwords_orig(text):
    global filtered_words
    stopWords = set(stopwords.words('english'))
    
    filtered_words = []
    for w in text:
        if w not in stopWords:
            filtered_words.append(w)
            filtered_words.append(' ')
           
    return "".join(filtered_words)

In [54]:
pdf_stop = []

for word in pdf_contra:
    word = word.lower()
    token = word_tokenize(word)
    no_stopwords = remove_stopwords_orig(token)
    pdf_stop.append(no_stopwords.strip())

pdf_stop

['humanitarians increasingly incorporate climate data forecasts analysis planning',
 'guidance series developed help humanitarians access analyze interpret common types climate weather data provide common language working meteorological hydrological services',
 'key takeaways observational rainfall data chirps arc captures much rain fallen defined period time']

### Spelling

In [55]:
from autocorrect import Speller

def check_spelling(text):
    spellcheck = Speller(lang='en')
    return spellcheck(text)

In [56]:
pdf_spell = []

for word in pdf_stop:
    # token = word_tokenize(word)
    corr_spell = check_spelling(word)
    pdf_spell.append(corr_spell)
pdf_spell

['humanitarian increasingly incorporate climate data forecasts analysis planning',
 'guidance series developed help humanitarian access analyze interpret common types climate weather data provide common language working meteorological hydrological services',
 'key takeaways observational rainfall data chirps arc captures much rain fallen defined period time']

### Stemming and Lemmatization

In [57]:
from nltk.stem.snowball import SnowballStemmer
from nltk.stem import WordNetLemmatizer

wlm = WordNetLemmatizer()
snowb_stem = SnowballStemmer(language='english')

In [58]:
pdf_final = []

for sentence in pdf_spell:
    sentence = word_tokenize(sentence)
    pdf_final.append(sentence)

pdf_final_stem = [snowb_stem.stem(word) for sentence in pdf_final for word in sentence]
pdf_final_stem

['humanitarian',
 'increas',
 'incorpor',
 'climat',
 'data',
 'forecast',
 'analysi',
 'plan',
 'guidanc',
 'seri',
 'develop',
 'help',
 'humanitarian',
 'access',
 'analyz',
 'interpret',
 'common',
 'type',
 'climat',
 'weather',
 'data',
 'provid',
 'common',
 'languag',
 'work',
 'meteorolog',
 'hydrolog',
 'servic',
 'key',
 'takeaway',
 'observ',
 'rainfal',
 'data',
 'chirp',
 'arc',
 'captur',
 'much',
 'rain',
 'fallen',
 'defin',
 'period',
 'time']

In [59]:
pdf_final_lemm = [wlm.lemmatize(word, 'v') for sentence in pdf_final for word in sentence]
pdf_final_lemm

['humanitarian',
 'increasingly',
 'incorporate',
 'climate',
 'data',
 'forecast',
 'analysis',
 'plan',
 'guidance',
 'series',
 'develop',
 'help',
 'humanitarian',
 'access',
 'analyze',
 'interpret',
 'common',
 'type',
 'climate',
 'weather',
 'data',
 'provide',
 'common',
 'language',
 'work',
 'meteorological',
 'hydrological',
 'service',
 'key',
 'takeaways',
 'observational',
 'rainfall',
 'data',
 'chirp',
 'arc',
 'capture',
 'much',
 'rain',
 'fall',
 'define',
 'period',
 'time']